Code smells
JoeriRietjens/Mastermind pull request #62
Opened 2020-11-24 10:55 UTC by JoeriRietjens

Fixed smells

2020-11-24 12:27 UTC, SioravW requested changes
You broke the logic #gitBlame
Ik denk dat het niet meer werkt doordat je nu ipv this.code Board.code gebruikt (ook bij Row). Zie comments

2020-11-24 12:27 UTC, SioravW commented on MastermindLogic/src/main/java/nl/fhict/s3/mastermindlogic/entity/Board.java
> +        System.arraycopy(clues, 0, rowToCheck.clues, 0, clues.length);
Kan dit niet gewoon met rowToCheck.clues = getClues(rowToCheck.code)?

2020-11-24 12:27 UTC, SioravW commented on MastermindLogic/src/main/java/nl/fhict/s3/mastermindlogic/entity/Board.java
> +        Board.code = code;
Werkt dit? Volgens mij niet namelijk, want je roept nu de klasse Board aan, maar gaan instantie ervan. Hetzelfde bij regel 16

2020-11-24 12:27 UTC, SioravW commented on MastermindLogic/src/main/java/nl/fhict/s3/mastermindlogic/entity/Row.java
> +        Row.code = code;
Het zelfde als bij Board. Volgens mij werkt dit niet. Je roept geen instantie aan.

2020-11-24 12:27 UTC, SioravW commented on MastermindLogic/src/main/java/nl/fhict/s3/mastermindlogic/entity/Row.java
> +        Row.clues = clues;
Je roept geen instantie aan. Volgens mij werkt dit niet zo.

2020-11-30 14:53 UTC, bramvanderzee requested changes

2020-11-30 14:53 UTC, bramvanderzee commented on MastermindLogic/src/main/java/nl/fhict/s3/mastermindlogic/entity/Board.java
>      public EPinColour[] code = new EPinColour[4];
why is this not final?

2020-11-30 14:53 UTC, bramvanderzee commented on MastermindLogic/src/main/java/nl/fhict/s3/mastermindlogic/entity/Row.java
> +    private EPinColour[] guess = new EPinColour[4];
Doesnt this need to be final?

2020-11-30 14:54 UTC, bramvanderzee approved these changes

2020-11-30 14:58 UTC, merged